### ISSUE TITLE
Error without an existing and properly configured ~/.abide_dev.yaml

### ISSUE THREAD

**Issue by pocketgeek** [hsnodgrass/abide_dev_utils#4]
Error when running abide jira from_coverage -d rhel8-coverage-report.json SERVENG without a ~/.abide_dev.yaml
Traceback (most recent call last):
	12: from /usr/local/bin/abide:23:in `<main>'
	11: from /usr/local/bin/abide:23:in `load'
	10: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/exe/abide:6:in `<top (required)>'
	 9: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/cli.rb:33:in `execute'
	 8: from /Library/Ruby/Gems/2.6.0/gems/cmdparse-3.0.7/lib/cmdparse.rb:889:in `parse'
	 7: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/cli/jira.rb:107:in `execute'
	 6: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/jira.rb:88:in `client'
	 5: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/jira.rb:137:in `merge_options'
	 4: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/jira.rb:141:in `config'
	 3: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/config.rb:15:in `config_section'
	 2: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/config.rb:10:in `to_h'
	 1: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/config.rb:10:in `open'
/Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/config.rb:10:in `initialize': No such file or directory @ rb_sysopen - /Users/curtis.edge/.abide_dev.yaml (Errno::ENOENT)

Error when file exists but is configured incorrectly
Traceback (most recent call last):
	10: from /usr/local/bin/abide:23:in `<main>'
	 9: from /usr/local/bin/abide:23:in `load'
	 8: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/exe/abide:6:in `<top (required)>'
	 7: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/cli.rb:33:in `execute'
	 6: from /Library/Ruby/Gems/2.6.0/gems/cmdparse-3.0.7/lib/cmdparse.rb:889:in `parse'
	 5: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/cli/jira.rb:107:in `execute'
	 4: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/jira.rb:88:in `client'
	 3: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/jira.rb:137:in `merge_options'
---
	 2: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/jira.rb:141:in `config'
	 1: from /Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/config.rb:15:in `config_section'
/Library/Ruby/Gems/2.6.0/gems/abide_dev_utils-0.3.0/lib/abide_dev_utils/config.rb:11:in `to_h': undefined method `transform_keys' for nil:NilClass (NoMethodError)

**Comment by hsnodgrass** [comment]
Resolved with https://github.com/hsnodgrass/abide_dev_utils/tree/v0.4.2
